apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 15m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      version: 6.28.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: tanzu-continuousdelivery-resources
  interval: 15m
  timeout: 5m
  releaseName: external-dns
  values:
    sources:
    - contour-httpproxy
    - ingress
    provider: aws
    txtOwnerId: ${cluster_name}
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::074754820263:role/tap-dns-role
    aws:
      region: us-west-2
